### ISSUE TITLE
Unity log icon sign loading but not working

### ISSUE THREAD

**Issue by sullivanag** [Oppodelldog/IconSign#7]
[Player.log](https://github.com/user-attachments/files/17356702/Player.log)

Unity log attached.  The sign I have in my build menu is under furniture, and not the Misc tab that is mentioned in the description.

**Comment by Oppodelldog** [comment]
Thanks for the log, this basically looks good.
There's also a message from the PIeceManger saying it has been added
```[Debug  :Jotunn.Managers.PieceManager] Added piece iconsign | Token: $iconsign_name```

@sullivanag I guess so, but need to ask: Did you already discover the ingredients for the sign, which are: wood, coal, raspberry, blueberry, and the green swamps slime "guck"?

**Comment by Oppodelldog** [comment]
I tested the mods in combination, having no issue, I can see my signs and find the build piece.
```
[Info   :   BepInEx] Loading [Custom Graphics Settings 0.9.0]
[Info   :   BepInEx] Loading [ValheimHDTerrain 0.1.0]
[Info   :   BepInEx] Loading [badgers Valheim Skies 0.14.1]
[Info   :   BepInEx] Loading [Jotunn 2.20.3]
[Info   :   BepInEx] Loading [AReasonToFish 0.0.1]
[Info   :   BepInEx] Loading [IconSign 0.1.0]
[Info   :   BepInEx] Loading [Valheim Plus 0.9.14.0]
[Info   :   BepInEx] Loading [Display BepInEx Info In-Game 2.0.2]
[Info   :   BepInEx] Loading [Equipment and Quick Slots 2.1.13]
[Info   :   BepInEx] Loading [MassFarming 1.9]
```

Waiting for @sullivanag to reply regarding the necessary materials - actually this seems to be the only known reason for the behaviour.

**Comment by Oppodelldog** [comment]
@sullivanag wrote on nexus bub page that he can find the IconSign now that he discovered the "guck".
I added a note regarding these requirements to the mod description.
